server:
  port: 9001

spring:
  application:
    name: nacos-provider-payment
  cloud:
      nacos:
        discovery:
          server-addr: 39.96.3.100:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"