server:
  port: 7001

eureka:
  instance:
    hostname: enrekaServer-7001 #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址 ，集群互相观望
#      defaultZone: http://loclhost:7002/eureka/
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址 ，单机自己地址
      defaultZone: http://loclhost:7001/eureka/
  server:
    #自我保护状态默认开启
    enable-self-preservation: false #自定义关闭自我保护，保证不可以服务及时剔除
    eviction-interval-timer-in-ms: 2000 #不可通讯的时长



